some simple refactoring
harm-smits/42docs pull request #37
Opened 2021-04-29 21:13 UTC by leeoocca

Hey! I did some refactoring after finding a couple of typos. I think I may have gone a bit too far 😅 

`index.md`
- fix GitHub spelling

`libs/minilibx/*.md`
- fix typos
- rephrased some sentences
- fix mlx_xpm_file_to_image
- tables instead of lists where applicable
- tabs instead of spaces in code blocks
- consistency with acronyms and punctuation
- some other small styling fixes
- _also_ fix macOS spelling

Tell me what you think!

2021-04-29 21:53 UTC, harm-smits requested changes
Thanks for the contribution. I sincerely appreciate it. There are a few things left to do, namely:

1. I used spaces because, those are actually universal. I see you assumed tab size is `4`, whilst by default, its actually `8`. So you will have to create the file `_sass/custom/custom.scss` with the according contents:
```scss
code {
    tab-size: 4;
}
```

2. You should also add a `.editorconfig` file to make sure all the tab characters are rendered to 4 spaces, something like this will do the trick:
```editorconfig
[*.{md,scss}]
charset = utf-8
indent_style = tab
indent_size = 4
```

3. Adhere to the 80 column line limit as much as possible. There is one case where you removed a newline.

Besides that, everything is looking great!

Thanks in advance!

2021-04-29 21:53 UTC, harm-smits commented on libs/minilibx/images.md
> +order to read we can call the functions `mlx_xpm_file_to_image` and `mlx_png_file_to_image` accordingly. Do mind that `mlx_png_file_to_image` currently leaks memory.
Please adhere to the 80 col line limit.

2021-04-29 22:09 UTC, leeoocca commented
1. You're right, I assumed tab size was 4. I had already seen tabs here and there so I thought that would be fine. Turns out it isn't. I'm going to add the lines you suggested.
2. Yeah, makes sense. I'll add it right away.
3. Yes, my mistake!

Thank you for your work!

2021-04-29 22:18 UTC, leeoocca commented on libs/minilibx/images.md
> +order to read we can call the functions `mlx_xpm_file_to_image` and `mlx_png_file_to_image` accordingly. Do mind that `mlx_png_file_to_image` currently leaks memory.
Done!

2021-04-30 06:10 UTC, merged

2021-04-30 06:11 UTC, harm-smits commented
Thanks for the final changes! Merged.